FROM python:3.11
WORKDIR /app
COPY pyproject.toml poetry.lock /app/

RUN pip install poetry --no-cache-dir
RUN poetry config virtualenvs.create false
RUN poetry install --without dev --no-root

COPY . .

CMD ["celery", "-A", "celery_app.celery", "worker", "--loglevel=info", "--concurrency=5"]
