# Use Python base image to avoid permission issues
FROM python:3.11

RUN pip install flower redis

COPY ./scripts/wait-for-it.sh /wait-for-it.sh
COPY ./config/flowerconfig.py /flowerconfig.py

RUN chmod +x /wait-for-it.sh

CMD ["sh", "-c", "/wait-for-it.sh -t 0 redis:6379 -- celery --broker=redis://redis:6379/0  flower --conf=/flowerconfig.py"]

